In [47]:
import numpy as np

def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

def cross_entropy_error(y, t):
    delta = 1e-7
    
    return -np.sum(t * np.log(y+delta))

def numerical_gradient(f, x):
    h = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + h
        fxh1 = f(x) # f(x+h)
        
        x[idx] = tmp_val - h 
        fxh2 = f(x) # f(x-h)
        grad[idx] = (fxh1 - fxh2) / (2*h)
        
        x[idx] = tmp_val # 값 복원
        it.iternext()   
        
    return grad


class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)
        
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [48]:
net = simpleNet()
print(net.W)

[[-1.38089766  0.5113928   0.92470496]
 [-0.25526316 -0.38354466 -0.2506211 ]]


In [49]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

np.argmax(p)

[-1.05827544 -0.03835451  0.32926398]


2

In [50]:
t = np.array([0, 0, 1])
net.loss(x, t)

0.6637543254806231

In [51]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
dW

array([[ 0.07714105,  0.21391023, -0.29105128],
       [ 0.11571157,  0.32086535, -0.43657692]])